env:
  browser: true
  es2021: true
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - off
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'prettier'
